### ISSUE TITLE
Usage Example

### ISSUE THREAD

**Issue by Birdasaur** [Teragam/JFXShader#1]
Hi. This is really cool work you are doing getting custom shaders to work . I'm trying to understand how I might use your ShaderEffect support in my own apps. I looked at your BlendShape classes in your samples directory... I'm not 100% sure how I might apply it to my own Nodes.
Could you possibly make a barebones basic demo using your sample?  ie... main() => scene => pane => node => ??? Apply BlendShape effect ??? => success?  

I would be grateful and happy to help test it from there on.

**Comment by Teragam** [comment]
Hi. Yes, I'm happy to add a full example.
I will probably use the wiki for this.
More complex shader examples are already in the works, I will hopefully add those soon, with the next release.

**Comment by Teragam** [comment]
Update:
I have added a simple example to the [wiki](https://github.com/Teragam/JFXShader/wiki/Examples) and updated the [README](https://github.com/Teragam/JFXShader/blob/main/README.md) to include a small code snippet for using a custom effect shader.

**Comment by Birdasaur** [comment]
That example is exactly what I was hoping for. Thank you! I can't wait to try this!
