### ISSUE TITLE
Supports 3D vertex shaders so that you can play 3D games with Javafx

### ISSUE THREAD

**Issue by qq1053831109** [Teragam/JFXShader#7]
Supports 3D vertex shaders so that you can play 3D games with Javafx

**Comment by qq1053831109** [comment]
window can use opengles u can see https://github.com/husker-dev/jfx-win-es2

**Comment by Teragam** [comment]
Hi. It is possible to write custom 3D vertex shaders using a custom ShaderMaterial for 3D shapes.
I can create a small example of it and add it to the wiki.

Yes, I'm aware that the JavaFX source code technically has support for OpenGL on Windows.
However, the official release disables the export of this pipeline, while the project you linked rebuilds JavaFX with the export enabled, which is fascinating.
I could try to rewrite some code to support the new graphics pipeline.

**Comment by Teragam** [comment]
Update:
The library is compatible with custom JavaFX builds that enable the OpenGL support for Windows. Both 2D and 3D effects seem to work as expected.
I have also added an [example](https://github.com/Teragam/JFXShader/wiki/3D-Examples) of creating a custom ShaderMaterial to the wiki.
